with source_table as
(
    select *
    from {{ source('airbnb_source', 'listings') }}
),

transformed as
(
    select
        nullif(trim(id),'') as id,
        nullif(trim(listing_url),'') as listing_url,
        scrape_id,
        last_scraped,
        nullif(trim(source),'') as source,
        nullif(trim(name),'') as name,
        nullif(trim(description),'') as description,
        nullif(trim(neighborhood_overview),'') as neighborhood_overview,
        nullif(trim(picture_url),'') as picture_url,
        nullif(trim(host_id),'') as host_id,
        nullif(trim(host_url),'') as host_url,
        nullif(trim(host_name),'') as host_name,
        host_since,
        nullif(replace(trim(host_location), ',', ' |'), '') as host_location,
        nullif(trim(host_about),'') as host_about,
        nullif(trim(host_response_time),'') as host_response_time,
        nullif(trim(host_response_rate),'') as host_response_rate,
        nullif(trim(host_acceptance_rate),'') as host_acceptance_rate,
        host_is_superhost,
        nullif(trim(host_thumbnail_url),'') as host_thumbnail_url,
        nullif(trim(host_picture_url),'') as host_picture_url,
        nullif(trim(host_neighbourhood),'') as host_neighbourhood,
        host_listings_count,
        host_total_listings_count,
        nullif(trim(host_verifications),'') as host_verifications,
        host_has_profile_pic,
        nullif(trim(host_identity_verified),'') as host_identity_verified,
        nullif(trim(neighbourhood),'') as neighbourhood,
        nullif(trim(neighbourhood_cleansed),'') as neighbourhood_cleansed,
        nullif(trim(neighbourhood_group_cleansed),'') as neighbourhood_group_cleansed,
        latitude,
        longitude,
        nullif(trim(property_type),'') as property_type,
        nullif(trim(room_type),'') as room_type,
        accommodates,
        bathrooms,
        nullif(trim(bathrooms_text),'') as bathrooms_text,
        bedrooms,
        beds,
        nullif(trim(amenities),'') as amenities,
        nullif(trim(price),'') as price,
        minimum_nights,
        maximum_nights,
        minimum_minimum_nights,
        maximum_minimum_nights,
        minimum_maximum_nights,
        maximum_maximum_nights,
        minimum_nights_avg_ntm,
        maximum_nights_avg_ntm,
        calendar_updated,
        has_availability,
        availability_30,
        availability_60,
        availability_90,
        availability_365,
        nullif(trim(calendar_last_scraped),'') as calendar_last_scraped,
        number_of_reviews,
        number_of_reviews_ltm,
        number_of_reviews_l30d,
        availability_eoy,
        number_of_reviews_ly,
        estimated_occupancy_l365d,
        estimated_revenue_l365d,
        nullif(trim(first_review),'') as first_review,
        nullif(trim(last_review),'') as last_review,
        review_scores_rating,
        review_scores_accuracy,
        review_scores_cleanliness,
        review_scores_checkin,
        review_scores_communication,
        review_scores_location,
        review_scores_value,
        nullif(trim(license),'') as license,
        instant_bookable,
        calculated_host_listings_count,
        calculated_host_listings_count_entire_homes,
        calculated_host_listings_count_private_rooms,
        calculated_host_listings_count_shared_rooms,
        reviews_per_month,
        nullif(trim(city_name),'') as city_name
    from
        source_table
)
select
    *
from
    transformed